import { ProviderProject, PricingPlan, ApiConsumer, ProviderApiKey, ProjectVersion } from '../../types/apibuild';
import { AlertRule, DetailedEndpoint, DeploymentRecord, ExtendedLogEntry, ExtendedVersion, KlyraInsightItem, MonitoringIncident } from './types';

export const DUMMY_PROJECT_ID = 'demo-atlas-commerce-api';

const plans: PricingPlan[] = [
  { id: 'atlas-free', name: 'Free', requestsPerMonth: 10000, priceMonthly: 0, rateLimitPerMin: 60, overagePer1k: 0, trialDays: 0, subscribers: 148 },
  { id: 'atlas-pro', name: 'Pro', requestsPerMonth: 1000000, priceMonthly: 49, rateLimitPerMin: 600, overagePer1k: 0.4, trialDays: 14, subscribers: 36 },
  { id: 'atlas-enterprise', name: 'Enterprise', requestsPerMonth: 10000000, priceMonthly: 299, rateLimitPerMin: 5000, overagePer1k: 0.2, trialDays: 30, subscribers: 8 },
];

const consumers: ApiConsumer[] = [
  { id: 'consumer-northstar', name: 'Northstar Retail', email: 'platform@northstar.example', plan: 'Enterprise', status: 'active', requests: 842190, joinedAt: '2026-05-12' },
  { id: 'consumer-lumen', name: 'Lumen Logistics', email: 'dev@lumen.example', plan: 'Pro', status: 'active', requests: 284911, joinedAt: '2026-06-03' },
  { id: 'consumer-pine', name: 'Pine Labs', email: 'api@pine.example', plan: 'Free', status: 'trialing', requests: 14220, joinedAt: '2026-08-18' },
];

const versions: ProjectVersion[] = [
  { id: 'atlas-v2-4-1', semver: 'v2.4.1', status: 'published', notes: 'Stable catalog and checkout release', createdAt: '2026-08-26T09:00:00.000Z', endpoints: 18 },
  { id: 'atlas-v2-4-0', semver: 'v2.4.0', status: 'deprecated', notes: 'Added bulk fulfillment operations', createdAt: '2026-07-19T09:00:00.000Z', endpoints: 17 },
  { id: 'atlas-v1-9-0', semver: 'v1.9.0', status: 'deprecated', notes: 'Legacy order contract', createdAt: '2026-03-11T09:00:00.000Z', endpoints: 14 },
];

const endpoints: DetailedEndpoint[] = [
  { id: 'ep-products', method: 'GET', path: '/v2/products', summary: 'List catalog products', description: 'Returns a cursor-paginated product catalog with inventory status.', category: 'Catalog', authRequired: true, rateLimitPerMin: 600, avgLatencyMs: 84, p95LatencyMs: 160, totalRequests: 482190, errorRate: 0.4, isHealthy: true, status: 'active', parameters: [{ name: 'cursor', in: 'query', type: 'string', required: false, description: 'Pagination cursor' }], responses: [{ statusCode: 200, description: 'Product page', schema: 'ProductPage', sampleBody: '{"data":[]}' }] },
  { id: 'ep-product', method: 'GET', path: '/v2/products/{productId}', summary: 'Retrieve a product', description: 'Returns one product and its current availability.', category: 'Catalog', authRequired: true, rateLimitPerMin: 600, avgLatencyMs: 61, p95LatencyMs: 119, totalRequests: 321440, errorRate: 0.2, isHealthy: true, status: 'active', parameters: [{ name: 'productId', in: 'path', type: 'string', required: true, description: 'Product identifier' }], responses: [{ statusCode: 200, description: 'Product', schema: 'Product', sampleBody: '{"id":"prod_123"}' }] },
  { id: 'ep-orders', method: 'POST', path: '/v2/orders', summary: 'Create an order', description: 'Creates an order and begins fulfillment orchestration.', category: 'Orders', authRequired: true, rateLimitPerMin: 300, avgLatencyMs: 142, p95LatencyMs: 294, totalRequests: 198220, errorRate: 1.1, isHealthy: true, status: 'active', parameters: [], requestBody: { contentType: 'application/json', schema: 'CreateOrder', sampleBody: '{"items":[]}' }, responses: [{ statusCode: 201, description: 'Order created', schema: 'Order', sampleBody: '{"id":"ord_123","status":"accepted"}' }] },
  { id: 'ep-refunds', method: 'POST', path: '/v2/refunds', summary: 'Issue a refund', description: 'Issues a full or partial refund against a settled order.', category: 'Payments', authRequired: true, rateLimitPerMin: 120, avgLatencyMs: 209, p95LatencyMs: 410, totalRequests: 28910, errorRate: 2.4, isHealthy: true, status: 'beta', parameters: [], responses: [{ statusCode: 202, description: 'Refund accepted', schema: 'Refund', sampleBody: '{"status":"pending"}' }] },
  { id: 'ep-legacy', method: 'GET', path: '/v1/orders/{orderId}', summary: 'Retrieve a legacy order', description: 'Deprecated v1 order representation. Migrate to the v2 contract.', category: 'Legacy', authRequired: true, rateLimitPerMin: 120, avgLatencyMs: 98, p95LatencyMs: 210, totalRequests: 8420, errorRate: 0.7, isHealthy: true, status: 'deprecated', parameters: [{ name: 'orderId', in: 'path', type: 'string', required: true, description: 'Order identifier' }], responses: [{ statusCode: 200, description: 'Legacy order', schema: 'LegacyOrder', sampleBody: '{"id":"ord_123"}' }] },
];

const deployment: DeploymentRecord = { id: 'dep-atlas-241', version: 'v2.4.1', environment: 'production', source: 'GitHub', branch: 'main', commitHash: '8f31c2a', commitMessage: 'Harden refund idempotency', region: 'Global edge', status: 'healthy', url: 'https://api.atlas-commerce.klyra.dev', deployedAt: '2026-08-26 09:14 UTC', durationSec: 42, author: 'Priya Nair', logs: ['Schema validation passed', 'TLS certificate verified', 'Route table propagated to 42 edge locations', 'Zero-downtime cutover complete'], envVars: [{ key: 'BASE_URL', value: 'https://origin.atlas-commerce.example', isSecret: false }, { key: 'PAYMENTS_TOKEN', value: 'vault://••••••••', isSecret: true }] };

const trace = [{ stage: 'DNS Resolution', durationMs: 3 }, { stage: 'SSL/TLS Handshake', durationMs: 12 }, { stage: 'Gateway Policy', durationMs: 8 }, { stage: 'Upstream', durationMs: 91 }, { stage: 'Response', durationMs: 7 }];
const logs: ExtendedLogEntry[] = [
  { id: 'trace-1001', timestamp: '2026-09-11T10:14:32.184Z', method: 'POST', path: '/v2/orders', statusCode: 201, latencyMs: 121, consumerName: 'Northstar Retail', keyPrefix: 'kly_live_nort', version: 'v2.4.1', region: 'us-east-1', ipAddress: '203.0.113.18', requestHeaders: { 'x-request-id': 'req_1001' }, queryParams: {}, requestBody: '{"items":3}', responseHeaders: { 'x-klyra-trace': 'trace-1001' }, responseBody: '{"status":"accepted"}', trace },
  { id: 'trace-1002', timestamp: '2026-09-11T10:13:18.091Z', method: 'GET', path: '/v2/products', statusCode: 200, latencyMs: 84, consumerName: 'Lumen Logistics', keyPrefix: 'kly_live_lume', version: 'v2.4.1', region: 'eu-west-1', ipAddress: '203.0.113.42', requestHeaders: { 'x-request-id': 'req_1002' }, queryParams: { cursor: 'next_page' }, requestBody: '', responseHeaders: { 'cache-control': 'private' }, responseBody: '{"data":[{"id":"prod_123"}]}', trace },
  { id: 'trace-1003', timestamp: '2026-09-11T10:11:04.552Z', method: 'POST', path: '/v2/refunds', statusCode: 500, latencyMs: 812, consumerName: 'Northstar Retail', keyPrefix: 'kly_live_nort', version: 'v2.4.1', region: 'ap-southeast-1', ipAddress: '203.0.113.18', requestHeaders: { 'x-request-id': 'req_1003' }, queryParams: {}, requestBody: '{"amount":1200}', responseHeaders: { 'retry-after': '2' }, responseBody: '{"error":"upstream_timeout"}', trace: [...trace.slice(0, 4), { stage: 'Response', durationMs: 698 }] },
];

export const DUMMY_PROJECT: ProviderProject = {
  id: DUMMY_PROJECT_ID, name: 'Atlas Commerce API', slug: 'atlas-commerce', description: 'Commerce infrastructure for catalog, checkout, fulfillment, and refunds.', category: 'E-commerce', status: 'published', environment: 'production', version: 'v2.4.1', sourceKind: 'github', baseUrl: 'https://origin.atlas-commerce.example', openApiUrl: 'https://api.atlas-commerce.example/openapi.json', gatewayUrl: 'https://api.atlas-commerce.klyra.dev', authKind: 'bearer', rateLimitPerMin: 600, healthCheckPath: '/health', requests: 1010760, requestsLabel: '1.0M requests', successRate: 99.2, latencyMs: 112, consumers: consumers.length, revenue: 13972, endpointCount: 18, schemaCount: 24, visibility: 'public', published: true, createdAt: '2026-03-11T09:00:00.000Z', updatedAt: '2026-09-11T10:14:32.184Z', deployment: { kind: 'klyra', status: 'healthy', providerUrl: deployment.url, source: 'GitHub', branch: 'main', environment: 'production', version: 'v2.4.1', lastHealthCheck: '12 seconds ago', log: deployment.logs }, detection: { openApiVersion: '3.1.0', endpointCount: 18, schemaCount: 24, authKind: 'Bearer Token', baseUrl: 'https://origin.atlas-commerce.example', endpoints: [], found: true, reachable: true, latencyMs: 112, title: 'Atlas Commerce API', description: 'Commerce infrastructure API' }, plans, consumersList: consumers, apiKeys: [{ id: 'key-atlas-northstar', label: 'Northstar production', prefix: 'kly_live_nort', consumer: 'Northstar Retail', plan: 'Enterprise', createdAt: '2026-05-12', lastUsed: 'Just now', revoked: false }, { id: 'key-atlas-lumen', label: 'Lumen staging', prefix: 'kly_test_lume', consumer: 'Lumen Logistics', plan: 'Pro', createdAt: '2026-06-03', lastUsed: '4 minutes ago', revoked: false }], versions, activity: [{ id: 'audit-1', label: 'Promoted v2.4.1 to production', at: '2026-08-26T09:14:32.000Z', kind: 'deploy' }, { id: 'audit-2', label: 'Rotated Northstar production key', at: '2026-08-24T16:22:00.000Z', kind: 'security' }, { id: 'audit-3', label: 'Updated refund endpoint policy', at: '2026-08-20T11:04:00.000Z', kind: 'config' }], corsOrigins: 'https://app.atlas-commerce.example', cacheTtlSeconds: 60, retryStrategy: 'Exponential backoff', connectTimeoutMs: 3000, requestTimeoutMs: 10000, stripBasePath: false, authHeaderName: 'Authorization', tags: 'commerce, payments, production', ipAllowlist: '10.0.0.0/8',
};

export const getDummyEndpoints = () => endpoints;
export const getDummyVersions = (): ExtendedVersion[] => versions.map((version, index) => ({ id: version.id, semver: version.semver, status: index === 0 ? 'Current' : 'Deprecated', isDefault: index === 0, releasedAt: version.createdAt, endpointsCount: version.endpoints, consumersCount: index === 0 ? 3 : 1, trafficPercentage: index === 0 ? 91 : index === 1 ? 8 : 1, successRate: index === 0 ? 99.2 : 98.4, avgLatencyMs: index === 0 ? 112 : 168, changelog: { added: index === 0 ? ['/v2/refunds'] : [], modified: index === 0 ? ['Idempotent order creation'] : [], deprecated: index === 1 ? ['/v1/orders/{orderId}'] : [], breaking: [] } }));
export const getDummyDeployments = () => [deployment];
export const getDummyLogs = () => logs;
export const getDummyInsights = (): KlyraInsightItem[] => [{ id: 'insight-1', category: 'Performance', severity: 'warning', title: 'Refund latency is above your SLO', description: 'P95 latency crossed 400ms in ap-southeast-1.', actionText: 'Inspect logs', actionType: 'navigate_tab', targetTab: 'logs' }, { id: 'insight-2', category: 'Version', severity: 'info', title: '8% of traffic still uses v2.4.0', description: 'Set a sunset date to move remaining consumers.', actionText: 'Review versions', actionType: 'navigate_tab', targetTab: 'versions' }];
export const getDummyIncidents = (): MonitoringIncident[] => [{ id: 'incident-1', title: 'Refund upstream timeout', severity: 'Major', status: 'Monitoring', startedAt: '2026-09-11T10:11:04.552Z', affectedEndpoints: ['/v2/refunds'], summary: 'Elevated upstream timeout rate in ap-southeast-1.' }];
export const getDummyAlertRules = (): AlertRule[] => [{ id: 'alert-1', name: 'Refund error rate', metric: 'error_rate', condition: '>', threshold: 5, unit: '%', durationSec: 300, channels: ['Slack', 'Email'], enabled: true }, { id: 'alert-2', name: 'P95 latency SLO', metric: 'p95_latency', condition: '>', threshold: 400, unit: 'ms', durationSec: 300, channels: ['Email'], enabled: true }];
